classDiagram
    class Produit {
         String référence
         String nom
         String description
         Float prix
         String catégorie
         Integer stock
         String image
    }
